dungeon_purpose_original_use = [
  "Ancestral Rites",
  "Arcane Library",
  "Astral Trading Hub",
  "Bestial Creations",
  "Breeding Grounds",
  "Burial Site",
  "Celestial Observations",
  "Covert Experiments",
  "Forbidden Trysts",
  "Forge for a Great Weapon",
  "Hideout",
  "Impenetrable Vault",
  "Invasion of Dreams",
  "Isolated Refuge",
  "Military Outpost",
  "Observatory",
  "Pilgrimage Site",
  "Protection of Rare Artifacts",
  "Secret Meeting Place",
  "Treasure Horde"
]

dungeon_purpose_built_by = [
  "A Fallen Hero",
  "A Fanatical Cult",
  "A Forgotten Empire",
  "A Long-Dead Poet",
  "A Militant Order",
  "A Renowned Alchemist",
  "A Royal Dynasty",
  "A Secret Society",
  "A Tyrannical Ruler",
  "A Warrior Tribe",
  "A Wealthy Recluse",
  "Desperate Rebels",
  "Heretical Alchemists",
  "Heretical Monks",
  "Immoral Sorcerers",
  "Inverted Astrologers",
  "Mob Families",
  "Opulent Merchants",
  "Pilgrims to a Dead God",
  "Rogue Scholars"
]