dungeon_history_purpose_original_use = [
  "Ancestral Rites",
  "Arcane Library",
  "Astral Trading Hub",
  "Bestial Creations",
  "Breeding Grounds",
  "Burial Site",
  "Celestial Observations",
  "Covert Experiments",
  "Forbidden Trysts",
  "Forge for a Great Weapon",
  "Hideout",
  "Impenetrable Vault",
  "Invasion of Dreams",
  "Isolated Refuge",
  "Military Outpost",
  "Observatory",
  "Pilgrimage Site",
  "Protection of Rare Artifacts",
  "Secret Meeting Place",
  "Treasure Horde"
]

dungeon_history_purpose_built_by = [
  "A Fallen Hero",
  "A Fanatical Cult",
  "A Forgotten Empire",
  "A Long-Dead Poet",
  "A Militant Order",
  "A Renowned Alchemist",
  "A Royal Dynasty",
  "A Secret Society",
  "A Tyrannical Ruler",
  "A Warrior Tribe",
  "A Wealthy Recluse",
  "Desperate Rebels",
  "Heretical Alchemists",
  "Heretical Monks",
  "Immoral Sorcerers",
  "Inverted Astrologers",
  "Mob Families",
  "Opulent Merchants",
  "Pilgrims to a Dead God",
  "Rogue Scholars"
]

dungeon_history_construction_entrance = [
  "A Creature’s Lair",
  "A Dream",
  "A Massive Tree",
  "A Well",
  "An Enormous Grave",
  "Behind a Waterfall",
  "Between Menhirs",
  "Cave",
  "Center of a Maze",
  "Cliff door",
  "Hollow Statue",
  "Illusory Wall",
  "Mine Shaft",
  "Sinking Sand",
  "Skyward Beam of Light",
  "Starlight Path",
  "Through a Painting",
  "Under a Bridge",
  "Underwater Tunnel",
  "Veil of Mist"
]

dungeon_history_construction_composition = [
  "Bone",
  "Coral",
  "Crystal",
  "Earth",
  "Ethereal Fabric",
  "Flesh",
  "Floating Platforms",
  "Fungi",
  "Glass",
  "Ice",
  "Living Plants",
  "Marble",
  "Metal",
  "Obsidian",
  "Petrified Wood",
  "Sand",
  "Shadow Material",
  "Stone",
  "Webs",
  "Wood"
]

dungeon_history_ruination_condition = [
  "Corpse",
  "Crumbling",
  "Cursed",
  "Desecrated",
  "Devoured",
  "Displaced",
  "Divided",
  "Frozen",
  "Haunted",
  "Infested",
  "Overgrown",
  "Overpopulated",
  "Petrified",
  "Plundered",
  "Poisoned",
  "Scorched",
  "Shrouded in Mist",
  "Submerged",
  "Unending",
  "Warped"
]

dungeon_history_ruination_cause = [
  "Alchemical Accident",
  "Ancient Curse",
  "Cataclysmic Flood",
  "Civil War",
  "Competing Rituals",
  "Consumed by a Beast",
  "Disease",
  "Hedonism",
  "Invasion",
  "Long-Term Abandonment",
  "Magic Gone Awry",
  "Magical Seal",
  "Natural Disaster",
  "Natural Erosion",
  "Obfuscation",
  "Overrun with Monsters",
  "Sudden Change in Climate",
  "Teleported to Another Realm",
  "Turned to Stone",
  "Unresolved Spirits"
]