const dungeonRooms = [
    {
        roll: 5,
        room: {
            type: "Trap",
            title1: "Action",
            title2: "Trigger",
            data1: [
                "ages",
                "burns",
                "captures",
                "carries",
                "confuses",
                "crushes",
                "curses",
                "cuts",
                "deafens",
                "drops",
                "drowns",
                "freezes",
                "glues",
                "hypnotizes",
                "impales",
                "infects",
                "lifts",
                "poisons",
                "shocks",
                "shoots"
            ],
            data2: [
                "activating",
                "breaking",
                "crossing",
                "disturbing",
                "entering",
                "extinguising",
                "focusing",
                "interacting",
                "lighting",
                "moving",
                "opening",
                "pulling",
                "pushing",
                "reading",
                "speaking",
                "stepping",
                "taking",
                "talking",
                "touching",
                "tripping"
            ]
        }
    },
    {
        roll: 4,
        room: {
            type: "Special",
            title1: "Object",
            title2: "Action",
            data1: [
                "books",
                "bridge",
                "contraption",
                "creature",
                "door",
                "flames",
                "furniture",
                "hole",
                "liquid",
                "mirror",
                "mural",
                "pool",
                "shadows",
                "smoke",
                "statue",
                "surface",
                "treasure",
                "voices",
                "wheel",
                "writing"
            ],
            data2: [
                "ages",
                "alarms",
                "animates",
                "attracts",
                "charges",
                "closes",
                "falls",
                "glows",
                "grows",
                "illusion",
                "levitates",
                "locks",
                "opens",
                "reflects",
                "repels",
                "reveals",
                "shifts",
                "silences",
                "teleports",
                "transforms"
            ]
        }
    },
    {
        roll: 2,
        room: {
            type: "Lore",
            title1: "Room Type",
            title2: "Clue",
            data1: [
                "armory",
                "barracks",
                "bath",
                "cistern",
                "court",
                "crypt",
                "den",
                "dining hall",
                "guard post",
                "infirmary",
                "kitchen",
                "latrine",
                "library",
                "shrine",
                "smith",
                "stable",
                "storage",
                "study",
                "vault",
                "workshop"
            ],
            data2: [
                "decay",
                "decor",
                "draft",
                "echoes",
                "footprints",
                "leavings",
                "light",
                "markings",
                "moisture",
                "noise",
                "paraphenalia",
                "residue",
                "scurrying",
                "signs",
                "smell",
                "stains",
                "tapping",
                "temperature",
                "vibrations",
                "writing"
            ]
        }
    },
    {
        roll: 1,
        room: {
            type: "Monster",
            title1: "Group",
            title2: "Activity",
            data1: [
                "avian",
                "beast",
                "behemoth",
                "construct",
                "demon",
                "extraplanar",
                "fey",
                "giant",
                "goblinoid",
                "humanoid",
                "hybrid",
                "incorporeal",
                "insectoid",
                "lizard",
                "magical",
                "mythical",
                "plant",
                "shape shifter",
                "undead",
                "unusual"
            ],
            data2: [
                "building",
                "devouring",
                "dying",
                "fighting",
                "growing",
                "haunting",
                "hiding",
                "killing",
                "mating",
                "mourning",
                "patrolling",
                "praying",
                "protection",
                "recuperating",
                "scheming",
                "sleeping",
                "stalking",
                "torturing",
                "training",
                "trapped"
            ]
        }
    }
]